services:
  - type: web
    name: whatsapp-bot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 src/app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard