services:
  - type: web
    name: whatsapp-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 src/app.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
